export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_COMMENTS_FOR_POST = 'GET_COMMENTS_FOR_POST';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CLEAR_POST_DETAILS = 'CLEAR_POST_DETAILS';
export const CLEAR_COMMETS = 'CLEAR_COMMETS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
